name: Deploy Portfolio

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Debug SSH setup
      env:
        AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
        LIGHTSAIL_HOST: ${{ secrets.LIGHTSAIL_HOST }}
        LIGHTSAIL_USERNAME: ${{ secrets.LIGHTSAIL_USERNAME }}
      run: |
        # Display debug info (safely)
        echo "Setting up SSH connection..."
        echo "Host: $LIGHTSAIL_HOST"
        echo "Username: $LIGHTSAIL_USERNAME"
        
        # Setup SSH directory
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        
        # Create and check key file
        echo "$AWS_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/lightsail.pem
        chmod 600 ~/.ssh/lightsail.pem
        
        # Verify key file content (safely)
        echo "Key file permissions:"
        ls -la ~/.ssh/lightsail.pem
        
        # Add host to known_hosts
        ssh-keyscan -t rsa $LIGHTSAIL_HOST >> ~/.ssh/known_hosts
        
        # Test connection with verbose output
        ssh -v -i ~/.ssh/lightsail.pem -o StrictHostKeyChecking=no $LIGHTSAIL_USERNAME@$LIGHTSAIL_HOST exit

    - name: Deploy to Lightsail
      if: success()
      env:
        AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
        LIGHTSAIL_HOST: ${{ secrets.LIGHTSAIL_HOST }}
        LIGHTSAIL_USERNAME: ${{ secrets.LIGHTSAIL_USERNAME }}
      run: |
        # Deploy the built files
        scp -i ~/.ssh/lightsail.pem -o StrictHostKeyChecking=no -r dist/* $LIGHTSAIL_USERNAME@$LIGHTSAIL_HOST:/var/www/html/