name: Deploy Portfolio

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: AWS_PRIVATE_KEY  # Change this to match your environment name exactly

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Check Environment Variables
      run: |
        if [ -z "${{ secrets.AWS_PRIVATE_KEY }}" ]; then
          echo "❌ AWS_PRIVATE_KEY is not set"
          exit 1
        else
          echo "✅ AWS_PRIVATE_KEY is set"
        fi
        
        if [ -z "${{ secrets.LIGHTSAIL_HOST }}" ]; then
          echo "❌ LIGHTSAIL_HOST is not set"
          exit 1
        else
          echo "✅ LIGHTSAIL_HOST is set"
        fi
        
        if [ -z "${{ secrets.LIGHTSAIL_USERNAME }}" ]; then
          echo "❌ LIGHTSAIL_USERNAME is not set"
          exit 1
        else
          echo "✅ LIGHTSAIL_USERNAME is set"
        fi

    - name: Debug SSH setup
      env:
        AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
        LIGHTSAIL_HOST: ${{ secrets.LIGHTSAIL_HOST }}
        LIGHTSAIL_USERNAME: ${{ secrets.LIGHTSAIL_USERNAME }}
      run: |
        # Create debug log
        echo "Debug Information:" > ~/deploy-debug.log
        echo "Time: $(date)" >> ~/deploy-debug.log
        echo "Working Directory: $(pwd)" >> ~/deploy-debug.log
        
        # Setup SSH with logging
        echo "Setting up SSH..." >> ~/deploy-debug.log
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "SSH directory created" >> ~/deploy-debug.log
        
        # Write key file with verification
        echo "$AWS_PRIVATE_KEY" > ~/.ssh/lightsail.pem
        chmod 600 ~/.ssh/lightsail.pem
        if [ -s ~/.ssh/lightsail.pem ]; then
          echo "Key file created successfully" >> ~/deploy-debug.log
          echo "Key file size: $(wc -c < ~/.ssh/lightsail.pem) bytes" >> ~/deploy-debug.log
        else
          echo "❌ Key file is empty" >> ~/deploy-debug.log
          exit 1
        fi
        
        # Show debug log
        cat ~/deploy-debug.log

        # Test SSH connection with debugging
        ssh -v -i ~/.ssh/lightsail.pem -o StrictHostKeyChecking=no $LIGHTSAIL_USERNAME@$LIGHTSAIL_HOST "echo 'SSH connection test'"

    - name: Deploy to Lightsail
      if: success()
      env:
        AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
        LIGHTSAIL_HOST: ${{ secrets.LIGHTSAIL_HOST }}
        LIGHTSAIL_USERNAME: ${{ secrets.LIGHTSAIL_USERNAME }}
      run: |
        scp -i ~/.ssh/lightsail.pem -o StrictHostKeyChecking=no -r dist/* $LIGHTSAIL_USERNAME@$LIGHTSAIL_HOST:/var/www/html/